import { Footer } from "@/components/atomic/organisms/footer/footer"
import { Navbar } from "@/components/atomic/organisms/navbar/navbar"
import { SectionBlocks } from "@/components/atomic/organisms/sectionBlocks/sectionBlocks"
import { SectionBusiness } from "@/components/atomic/organisms/sectionBusiness/sectionBusiness"
import { SectionBusinessGallery } from "@/components/atomic/organisms/sectionBusinessGallery/sectionBusinessGallery"
import { SectionIdeas } from "@/components/atomic/organisms/sectionIdeas/sectionIdeas"
import { SectionSimilar } from "@/components/atomic/organisms/sectionSimilar/sectionSimilar"
import { SectionTeamBrainStorming } from "@/components/atomic/organisms/sectionTeamBrainStorming/sectionTeamBrainStorming"
import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>wrapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        menuItems={[
          { label: "Products", link: "#" },
          { label: "Solutions", link: "#" },
          { label: "Pricing", link: "#" },
          { label: "Resources", link: "#" }
        ]}
      />
      <SectionIdeas />
      <SectionBlocks />
      <SectionTeamBrainStorming />
      <SectionSimilar
        slides={[
          {
            img: "url('./img/sectionSimilar/woman.png')",
            topic: "Artist & investor",
            description: `Enim sagittis, sit porttitor morbi lobortis amet, libero
          adipiscing auctor. Malesuada tristique libero, id netus tincidunt.
          Egestas ac arcu amet nisl quis est ...`
          },

          {
            img: "url('./img/sectionSimilar/woman.png')",
            topic: "Artist & investor",
            description: `Enim sagittis, sit porttitor morbi lobortis amet, libero
          adipiscing auctor. Malesuada tristique libero, id netus tincidunt.
          Egestas ac arcu amet nisl quis est ...`
          },

          {
            img: "url('./img/sectionSimilar/woman.png')",
            topic: "Artist & investor",
            description: `Enim sagittis, sit porttitor morbi lobortis amet, libero
          adipiscing auctor. Malesuada tristique libero, id netus tincidunt.
          Egestas ac arcu amet nisl quis est ...`
          },
          {
            img: "url('./img/sectionSimilar/woman.png')",
            topic: "Artist & investor",
            description: `Enim sagittis, sit porttitor morbi lobortis amet, libero
          adipiscing auctor. Malesuada tristique libero, id netus tincidunt.
          Egestas ac arcu amet nisl quis est ...`
          },
          {
            img: "url('./img/sectionSimilar/woman.png')",
            topic: "Artist & investor",
            description: `Enim sagittis, sit porttitor morbi lobortis amet, libero
          adipiscing auctor. Malesuada tristique libero, id netus tincidunt.
          Egestas ac arcu amet nisl quis est ...`
          }
        ]}
      />
      <SectionBusiness />
      <SectionBusinessGallery />
      <Footer />
    </>
  )
}
