import { Navbar } from "@/components/atomic/organisms/navbar/navbar"
import { SectionIdeas } from "@/components/atomic/organisms/sectionIdeas/sectionIdeas"
import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>wrapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <SectionIdeas />
    </>
  )
}
